### ISSUE TITLE
Line Feeds in Comment Template?

### ISSUE THREAD

**Issue by BickiBoy** [CDuke/AutoMerge#18]
BTW - this is a huge time-saver for me. I'm Merging changes to 203 branches daily. This is awesome.

I tried to get creative on my Comments so I could ass some line feeds but it crashed Visual Studio.

Here's my conf file:
{
  "merge_operation_default": "last",
  "last_operation": "merge",
  "comment_format": "
Patch Back: {OriginalComment}  
(AutoMerge: {FromOriginalToTarget})
(Original Changeset: {SourceChangesetId})
"
}

And the error message:

System.ArgumentOutOfRangeException was unhandled
Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Length cannot be less than zero.

Visual Studio Error during debug:

![image](https://cloud.githubusercontent.com/assets/15882769/11202381/a4a918ca-8cb5-11e5-929f-607e4d76e597.png)

**Comment by SergeLalonde** [comment]
This issue was closed, but there's no comment on how to insert the line feeds.

If I want to put the merge branch history on a separate line, is it as simple as changing
{
  "comment_format": "{OriginalComment} (MERGE {FromOriginalToTarget})"
}
to be
{
  "comment_format": "{OriginalComment}
(MERGE {FromOriginalToTarget})"
}

Thanks.
